[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
