import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';import {parseHTML} from 'linkedom';
import * as speedLib from '../dist/speed.mjs';
import * as transportLib from '../dist/transport.mjs';
import * as movement from '../dist/movement.mjs';
import * as waveform from '../dist/waveform.mjs';import * as settings from '../dist/settings.mjs';import * as icons from '../dist/icons.mjs';
import * as core from '../dist/core.mjs';import * as projects from '../dist/projects.mjs';import * as dsp from '../dist/dsp.mjs';import * as effects from '../dist/effects.mjs';
const {document,window:domWindow}=parseHTML(fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8'));
const window={Event:domWindow.Event};
const elements=id=>document.getElementById(id),listeners=new Map(),storage=new Map();
for(const d of document.querySelectorAll('dialog')){Object.defineProperty(d,'open',{get:()=>d.hasAttribute('open')});d.showModal=()=>d.setAttribute('open','');d.close=()=>{d.removeAttribute('open');d.dispatchEvent(new window.Event('close'));};}
const selectProto=Object.getPrototypeOf(document.createElement('select'));Object.defineProperty(selectProto,'value',{get(){return this.querySelector('option[selected]')?.value||this.querySelector('option')?.value||'';},set(value){for(const o of this.querySelectorAll('option')){if(o.value===String(value))o.setAttribute('selected','');else o.removeAttribute('selected');}},configurable:true});
for(const el of document.querySelectorAll('input')){if(el.hasAttribute('checked'))el.checked=true;el.select=()=>{};}
Object.defineProperty(elements('timelineScroll'),'clientWidth',{value:1000});elements('timelineScroll').scrollLeft=0;elements('timelineScroll').scrollTop=0;elements('timelineScroll').getBoundingClientRect=()=>({left:100,right:1100,top:0,width:1000,height:400});
window.addEventListener=(k,f)=>{if(!listeners.has(k))listeners.set(k,new Set());listeners.get(k).add(f);};window.removeEventListener=(k,f)=>listeners.get(k)?.delete(f);window.innerWidth=1280;window.innerHeight=800;
document.elementFromPoint=()=>document.querySelector('.track');
const samples=Float32Array.from({length:441000},(_,i)=>.1*Math.sin(i/25));const buffer={duration:10,numberOfChannels:1,sampleRate:44100,length:samples.length,getChannelData:()=>samples};
class AudioContext{async decodeAudioData(){return buffer;}}
const context=vm.createContext({...speedLib,...transportLib,...movement,...waveform,...settings,...icons,...core,...projects,...dsp,...effects,console,document,window,crypto:globalThis.crypto,structuredClone,Float32Array,Blob,File,Map,Set,JSON,Math,URL,AudioContext,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},getComputedStyle:()=>({getPropertyValue:()=>174}),setTimeout:()=>0,clearTimeout(){},requestAnimationFrame:()=>1,cancelAnimationFrame(){},confirm:()=>true});
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*?;\n/gm,'').replaceAll('import.meta.url',JSON.stringify(new URL('../dist/app.js',import.meta.url).href));
vm.runInContext(source,context);const run=s=>vm.runInContext(s,context);
context.fixture=new File(['recording'],'Voice.wav',{type:'audio/wav'});await run('importFiles([fixture])');assert.equal(run('assets.size'),1);assert.equal(run('state.clips.length'),0);
const assetId=run('[...assets.keys()][0]');context.assetId=assetId;const nameInput=document.querySelector('[data-rename-asset]');nameInput.value='Nico';nameInput.onchange();run('addAsset(assetId,state.tracks[0].id,0)');assert.equal(run('clipName(state.clips[0])'),'Nico');
const event=(x,y=20)=>({button:0,clientX:x,clientY:y,preventDefault(){},stopPropagation(){}});const emit=(type,e)=>{for(const f of [...listeners.get(type)||[]])f(e);};
context.ev=event(474);run('pps=40;startScrub(ev)');assert.equal(run('cursor'),5);emit('pointermove',event(674));assert.equal(run('cursor'),10);assert.equal(run('playing'),false);emit('pointerup',event(674));
const clipEl=document.querySelector('.clip');clipEl.getBoundingClientRect=()=>({left:100,top:0,width:400,height:100});context.ev={...event(200,30),currentTarget:clipEl,target:clipEl.querySelector('[data-action="gain"]')};run('startDrag(ev)');emit('pointermove',event(200,50));emit('pointerup',event(200,50));assert(run('state.clips[0].gain')<1);
run('addAsset(assetId,state.tracks[0].id,8)');assert.equal(document.querySelectorAll('.cross-overlay').length,2);assert(document.querySelector('.cross-overlay [data-action="fadeOut"]'));assert(document.querySelector('.cross-overlay [data-action="fadeIn"]'));
const firstTrack=run('state.tracks[0].id');run('reorderTrack(state.tracks[0].id,state.tracks[2].id,true)');assert.equal(run('state.tracks[2].id'),firstTrack);run('undo()');assert.equal(run('state.tracks[0].id'),firstTrack);
run('editMarker()');elements('markerTitle').value='Introduction';elements('markerNote').value='Raccourcir la pause';elements('markerTime').value='3.25';elements('markerForm').onsubmit({preventDefault(){}});assert.equal(run('state.markers[0].note'),'Raccourcir la pause');assert.equal(document.querySelector('[data-marker]').textContent,'Introduction');
run("openFx('clip',state.clips[0].id);changeFx('enabled',true);changeFx('deess',40)");assert.equal(run('state.clips[0].fx.deess'),40);elements('fxDialog').close();
run("state.name='Projet A';cursor=3;pps=42;state.analysis={visible:true,results:{[assetId]:[{start:2,end:3}]}};");assert.equal(await run('saveProject()'),true);const savedId=run('projectId');const saved=await projects.readProject(savedId);assert.equal(saved.state.markers[0].title,'Introduction');assert.equal(saved.state.clips[0].fx.deess,40);assert.equal(saved.view.pps,42);
const copyPromise=run('saveProject(true)');elements('nameValue').value='Projet B';elements('nameForm').onsubmit({preventDefault(){}});assert.equal(await copyPromise,true);assert.notEqual(run('projectId'),savedId);assert.equal((await projects.readProject(savedId)).state.name,'Projet A');
context.savedId=savedId;assert.equal(await run('loadLocalProject(savedId)'),true);assert.equal(run('state.name'),'Projet A');assert.equal(run('cursor'),3);assert.equal(run('assets.size'),1);assert.equal(run('state.clips[0].fx.deess'),40);assert(document.querySelector('.hesitation-band'));
console.log('DOM intégré : import sans placement, renommage, scrub, gain, deux courbes, pistes, repères, FX, sauvegarde/sous et réouverture complète : OK.');
// Floating/docked inspector keeps exactly one live set of controls.
run('selected=state.clips[0].id;openInspector()');assert(elements('blockDialog').open);assert.equal(elements('inspectorContents').parentNode.id,'blockContents');assert(elements('inspectorPanel').hidden);
run("setInspectorMode('dock')");assert(!elements('blockDialog').open);assert(!elements('inspectorPanel').hidden);assert.equal(elements('inspectorContents').parentNode.id,'inspectorPanel');run("setInspectorMode('popup')");assert.equal(document.querySelectorAll('#clipVolume').length,1);elements('blockDialog').close();
// Drag, undo and lock; canceled note drafts do not alter saved marker state.
run('pps=40');let marker=document.querySelector('[data-marker]');marker.getBoundingClientRect=()=>({left:400,bottom:100});context.ev={...event(400),currentTarget:marker};const oldTime=run('state.markers[0].time');run('startMarkerDrag(ev)');emit('pointermove',event(480));emit('pointerup',event(480));assert.equal(run('state.markers[0].time'),oldTime+2);run('undo()');assert.equal(run('state.markers[0].time'),oldTime);
run('state.markers[0].locked=true;drawMarkers()');marker=document.querySelector('[data-marker]');marker.getBoundingClientRect=()=>({left:400,bottom:100});context.ev={...event(400),currentTarget:marker};run('startMarkerDrag(ev)');emit('pointermove',event(600));emit('pointerup',event(600));assert.equal(run('state.markers[0].time'),oldTime);assert(elements('markerTime').disabled);
elements('markerNote').value='Uncommitted';document.body.dispatchEvent(new window.Event('pointerdown',{bubbles:true}));assert(elements('markerPopover').hidden);assert.equal(run('state.markers[0].note'),'Raccourcir la pause');
// Wheel pinch keeps the time beneath the mouse fixed, ordinary scroll unaffected.
run('pps=40');elements('timelineScroll').scrollLeft=100;const anchor=(100+600-100-174)/40;const wheel=new window.Event('wheel',{cancelable:true});Object.assign(wheel,{ctrlKey:true,deltaY:-20,deltaMode:0,clientX:600});elements('timelineScroll').dispatchEvent(wheel);assert(wheel.defaultPrevented);assert(run('pps')>40);assert(Math.abs((elements('timelineScroll').scrollLeft+326)/run('pps')-anchor)<1e-9);
// Backdrop dismissal resolves askName as cancellation, slider release outside stays open.
const nameResult=run("askName('Test','Original')");const dialog=elements('nameDialog');dialog.getBoundingClientRect=()=>({left:100,right:500,top:100,bottom:300});const pointer=(type,x)=>{const e=new window.Event(type,{bubbles:true});Object.assign(e,{clientX:x,clientY:150});dialog.dispatchEvent(e);};pointer('pointerdown',200);pointer('pointerup',700);assert(dialog.open);elements('nameValue').value='Discarded';pointer('pointerdown',700);pointer('pointerup',700);assert.equal(await nameResult,null);assert(!dialog.open);
// Copy basic settings via UI and apply on another clip without moving it.
run('selected=state.clips[0].id;renderInspector()');elements('blockSettingsTools').querySelector('[data-settings-copy]').onclick();const position=run('state.clips[1].start');run('selected=state.clips[1].id;renderInspector()');elements('blockSettingsTools').querySelector('[data-settings-paste]').onclick();assert.equal(run('state.clips[1].fx.deess'),40);assert.equal(run('state.clips[1].start'),position);
console.log('Nouveaux gestes : repères glissés/verrouillés, pinch ancré, inspecteur flottant/ancré, copie et fermeture annulant les brouillons : OK.');
// Isolated arrangement for group movement, snapping and ripple interactions.
run(`state.clips=[{...state.clips[0],id:'a',start:1,duration:2,fadeIn:0,fadeOut:0,track:state.tracks[0].id},{...state.clips[0],id:'b',start:5,duration:1,fadeIn:0,fadeOut:0,track:state.tracks[0].id},{...state.clips[0],id:'c',start:8,duration:1,fadeIn:0,fadeOut:0,track:state.tracks[1].id}];pps=40;state.rippleMode='off';selectOnly('a');render();`);
elements('timelineScroll').scrollLeft=0;
function drag(id,dx,extra={}){const el=document.querySelector(`.clip[data-clip="${id}"]`);el.getBoundingClientRect=()=>({left:300,top:50,width:80,height:100});context.ev={...event(350,80),currentTarget:el,target:el,...extra};run('startDrag(ev)');emit('pointermove',{...event(350+dx,80),...extra});emit('pointerup',event(350+dx,80));}
drag('a',79);assert.equal(run("state.clips.find(c=>c.id==='a').start"),3); // end snaps to B start 5
run("undo();selectOnly('a');state.rippleMode='track';render()");drag('a',40,{altKey:true});assert.deepEqual(JSON.parse(run('JSON.stringify(state.clips.map(c=>c.start))')),[2,6,8]);run('undo()');
run("selectOnly('a');state.rippleMode='all';render()");drag('a',40,{altKey:true});assert.deepEqual(JSON.parse(run('JSON.stringify(state.clips.map(c=>c.start))')),[2,6,9]);run('undo()');
run("state.rippleMode='off';selectOnly('a');render()");const bEl=document.querySelector('.clip[data-clip="b"]');context.ev={...event(350),currentTarget:bEl,target:bEl,metaKey:true};run('startDrag(ev)');assert.equal(run('selectedClips().length'),2);drag('b',40,{altKey:true});assert.deepEqual(JSON.parse(run('JSON.stringify(state.clips.map(c=>c.start))')),[2,6,8]);run('undo()');
// Lasso across both track lanes selects by rectangle, ignoring nonintersecting C.
run('selectOnly(null);render()');for(const el of document.querySelectorAll('.clip')){const i=['a','b','c'].indexOf(el.dataset.clip);el.getBoundingClientRect=()=>({left:300+i*100,right:380+i*100,top:60,bottom:160});}
context.ev=event(290,50);run('startLasso(ev)');emit('pointermove',event(490,170));emit('pointerup',event(490,170));assert.deepEqual([...run('selectionIds()')],['a','b']);assert(elements('selection').textContent.includes('2 blocs sélectionnés'));
let confirmations=0;context.confirm=()=>{confirmations++;return false;};run("openFx('clip','a');changeFx('deess',65)");assert.notEqual(run('state.clips[0].fx.deess'),65);context.confirm=()=>{confirmations++;return true;};run("changeFx('deess',65)");assert.equal(run('state.clips[0].fx.deess'),65);assert.equal(run('state.clips[1].fx.deess'),65);assert.notEqual(run('state.clips[2].fx.deess'),65);assert.equal(confirmations,2);elements('fxDialog').close();
// Context menu retains separate full-settings and FX clipboards.
run("selectOnly('a');openClipMenu('a',500,100)");document.querySelector('[data-menu-action="copy-settings"]').onclick();run("openClipMenu('a',500,100)");document.querySelector('[data-menu-action="copy-fx"]').onclick();assert(run('blockClipboard.kind')==='clip'&&run('fxClipboard.kind')==='fx');run("selectOnly('c');openClipMenu('c',500,100)");document.querySelector('[data-menu-action="paste-fx"]').onclick();assert.equal(run('state.clips[2].fx.deess'),65);
run("state.tracks[0].snap=false;state.rippleMode='all';selectOnly('a');toggleSelection('b');");const recorded=run('captureProject()');assert.equal(recorded.state.tracks[0].snap,false);assert.equal(recorded.state.rippleMode,'all');assert.equal(recorded.view.selectedIds.length,2);
console.log('Groupes : Cmd+clic, lasso, déplacement commun, ripple, avertissement/annulation, FX collectifs et menu contextuel : OK.');
// A group cannot cross time zero; pointer cancellation restores every affected clip.
run("state.rippleMode='off';state.tracks[0].snap=true;state.clips[0].start=1;state.clips[1].start=5;selectOnly('a');toggleSelection('b');render()");drag('b',-400,{altKey:true});assert.equal(run('state.clips[0].start'),0);assert.equal(run('state.clips[1].start'),4);
const beforeCancel=run('JSON.stringify(state.clips)');const cancelEl=document.querySelector('.clip[data-clip="b"]');cancelEl.getBoundingClientRect=()=>({left:300,top:50,width:80,height:100});context.ev={...event(350,80),currentTarget:cancelEl,target:cancelEl};run('startDrag(ev)');emit('pointermove',{...event(390,80),altKey:true});emit('pointercancel',event(390,80));assert.equal(run('JSON.stringify(state.clips)'),beforeCancel);
console.log('Limite temporelle du groupe et annulation atomique du geste : OK.');
run("state.rippleMode='off';state.tracks[0].snap=0;render()");
for(const mode of ['track','all','off']){elements('rippleMode').onclick();assert.equal(run('state.rippleMode'),mode);}
for(const mode of [1,2,0]){document.querySelector('[data-snap]').onclick();assert.equal(run('state.tracks[0].snap'),mode);assert.equal(document.querySelector('[data-snap]').dataset.mode,String(mode));}
console.log('Boutons Suivi et Aimant : cycle complet 0 → 1 → 2 → 0 : OK.');
run('cursor=2;delete state.loop;state.zoneMode=false;drawLoop();openZone()');assert.equal(run('state.loop'),undefined);elements('zoneButton').onclick();assert.equal(run('state.loop'),undefined);assert.equal(elements('zoneDialog').open,false);run('state.loop={start:2,end:7,enabled:true};openZone()');assert.equal(run('state.loop.start'),2);elements('zoneLength').value='3';elements('zoneLength').onchange();assert.equal(run('state.loop.end'),5);elements('zoneDialog').close();
// Translate a loop without changing its length, then resize its end.
let region=elements('loopRegion');context.ev={...event(400),target:region};elements('loopLane').onpointerdown(context.ev);emit('pointermove',{...event(480),altKey:true});emit('pointerup',event(480));assert.equal(run('state.loop.start'),4);assert.equal(run('state.loop.end'),7);
context.ev={...event(400),target:elements('loopRegion').querySelector('[data-zone-edge="end"]')};elements('loopLane').onpointerdown(context.ev);emit('pointermove',event(440));emit('pointerup',event(440));assert.equal(run('state.loop.end'),8);
run('openExport(true)');assert.equal(elements('exportRange').value,'zone');elements('exportDialog').close();elements('playSpeed').value='1.5';elements('playSpeed').onchange({target:elements('playSpeed')});assert.equal(run('state.speed'),1.5);elements('gridPattern').value='dots';elements('gridOpacity').value='40';elements('gridPattern').onchange();assert(document.querySelector('.lane').style.backgroundImage.includes('radial-gradient'));assert.equal(run('captureProject().state.grid.opacity'),40);
// Verify source scheduling and export slicing through the actual app functions.
const scheduled=[];class FakeRenderContext{constructor(channels=2,length=1,rate=48000){this.currentTime=0;this.sampleRate=rate;this.length=length;this.channels=channels;this.destination={};}createGain(){return {gain:{value:1,setValueAtTime(){},linearRampToValueAtTime(){}},connect(){},disconnect(){}};}createBufferSource(){const src={playbackRate:{value:1},connect(){},disconnect(){},start(when,offset,duration){scheduled.push({when,offset,duration,rate:this.playbackRate.value});}};return src;}async startRendering(){return {getChannelData:()=>new Float32Array(this.length)};}}
context.effectChain=()=>({input:{},output:{connect(){}},disconnect(){}});context.prepareEffects=async()=>{};context.renderContext=new FakeRenderContext();
run("state.clips=[{...state.clips[0],start:1,offset:0,duration:8,fadeIn:0,fadeOut:0}];state.tracks.forEach(t=>{t.mute=false;t.solo=false});schedule(renderContext,3,renderContext.destination,{to:5,rate:2,speedBuffers:new Map([[state.clips[0].asset,assets.get(state.clips[0].asset).buffer]])})");assert.deepEqual(scheduled.at(-1),{when:.03,offset:1,duration:1,rate:1});
context.OfflineAudioContext=FakeRenderContext;let encoded=null;context.Worker=class{postMessage(message){encoded=message;this.onmessage({data:{blob:new Blob(['audio'])}});}terminate(){}};context.setTimeout=fn=>{fn();return 0;};run("download=()=>{};state.loop={start:3,end:5,enabled:true};state.speed=3;openExport(true)");assert.equal(await run('exportMix()'),true);assert.equal(encoded.channels[0].length,2*encoded.rate);assert.equal(scheduled.at(-1).offset,2);assert.equal(scheduled.at(-1).duration,2);assert.equal(scheduled.at(-1).rate,1);
console.log('Zone : translation, durée, export exact à ×1 ; vitesse de lecture et grille persistantes : OK.');

// Creation requires an actual drag; snap endpoints to flags, keep length on translation.
run("delete state.loop;state.zoneMode=true;state.markers=[{id:'flag',time:5,title:'Flag',color:'#ffcc88'}];pps=40;drawLoop()");
context.ev={...event(354),target:elements('loopLane')};elements('loopLane').onpointerdown(context.ev);emit('pointerup',event(354));assert.equal(run('state.loop'),undefined);
elements('loopLane').onpointerdown(context.ev);emit('pointermove',event(471));emit('pointerup',event(471));assert.equal(run('state.loop.start'),2);assert.equal(run('state.loop.end'),5);
context.ev={...event(400),target:elements('loopRegion')};elements('loopLane').onpointerdown(context.ev);emit('pointermove',event(518));emit('pointerup',event(518));assert.equal(run('state.loop.start'),5);assert.equal(run('state.loop.end'),8);
console.log('Mode Zone sans création implicite, clic sans effet, tracé aimanté et translation de durée constante : OK.');
run("cursor=3.456;editMarker()");assert.equal(elements('markerTime').value,'3.46');elements('cancelMarker').onclick();
run("selectOnly(null);render()");assert(elements('toggleInspector').disabled);run("selectOnly(state.clips[0].id);render()");assert(!elements('toggleInspector').disabled);assert(elements('toggleInspector').classList.contains('has-selection'));assert(!elements('fadeInInput'));assert(!elements('fadeOutInput'));
run("state.zoneMode=false;drawLoop()");assert(elements('loopRegion').hidden);elements('zoneButton').onclick();assert(!elements('loopRegion').hidden);elements('toggleMarkers').onclick();assert(elements('markers').hidden);elements('toggleMarkers').onclick();assert(!elements('markers').hidden);
run("state.markers=[{id:'moving',time:2,title:'M',note:'',color:'#ffcc88'},{id:'target',time:5,title:'T',note:'',color:'#ffcc88'}];drawMarkers()");let moving=document.querySelector('[data-marker="moving"]');moving.getBoundingClientRect=()=>({left:400,bottom:100});context.ev={...event(400),currentTarget:moving};run('startMarkerDrag(ev)');emit('pointermove',event(518));assert.equal(run('state.markers[0].time'),5);emit('pointermove',{...event(518),altKey:true});assert.equal(run('state.markers[0].time'),4.95);emit('pointerup',event(518));
elements('gridResolution').value='8';elements('gridResolution').onchange();assert.equal(run('state.grid.divisions'),8);run('drawGrid(160)');assert(document.querySelector('.lane').style.backgroundSize.includes('20px'));
console.log('Repères aimantés / Option libre, deux décimales, visibilité, état Bloc et résolution de grille : OK.');
Object.defineProperty(document,'activeElement',{value:document.body,configurable:true});context.PointerEvent=class{constructor(type,opts){this.type=type;Object.assign(this,opts);}};window.dispatchEvent=e=>emit(e.type,e);
run("state.markers[0].time=2;drawMarkers()");moving=document.querySelector('[data-marker="moving"]');moving.getBoundingClientRect=()=>({left:400,bottom:100});context.ev={...event(400),currentTarget:moving};emit('pointerdown',context.ev);run('startMarkerDrag(ev)');emit('pointermove',event(518));assert.equal(run('state.markers[0].time'),5);emit('keydown',{key:'Alt',altKey:true});assert.equal(run('state.markers[0].time'),4.95);emit('keyup',{key:'Alt',altKey:false});assert.equal(run('state.markers[0].time'),5);emit('pointerup',event(518));
console.log('Option pressée/relâchée sans mouvement de souris : aimant suspendu/rétabli immédiatement : OK.');
// Removing media excludes its bytes from saves and exports; undo restores it.
run("selectOnly(state.clips[0].id);render()");const mediaId=run('state.clips[0].asset');context.mediaId=mediaId;context.confirm=()=>false;run('removeAsset(mediaId)');assert(run('projectAssets().some(a=>a.id===mediaId)'));context.confirm=()=>true;run('removeAsset(mediaId)');assert(!run('projectAssets().some(a=>a.id===mediaId)'));assert.equal(run('state.clips.filter(c=>c.asset===mediaId).length'),0);assert(!run('captureProject().assets.some(a=>a.id===mediaId)'));run('undo()');assert(run('projectAssets().some(a=>a.id===mediaId)'));assert(run('state.clips.some(c=>c.asset===mediaId)'));run('undo(true)');assert(!run('captureProject().assets.some(a=>a.id===mediaId)'));
console.log('Retrait de fichier : confirmation, suppression des blocs, exclusion des sauvegardes/exports et annuler/rétablir : OK.');
// Scrubbing resumes only a previously running transport, after release.
run('undo();pps=40;state.tracks.forEach(t=>t.snap=0)');const resumes=[];context.recordResume=position=>resumes.push(position);run('play=()=>{recordResume(cursor);playing=true;}');
context.ev=event(474);run('playing=true;startScrub(ev)');assert.equal(run('playing'),false);emit('pointermove',event(514));assert.equal(resumes.length,0);emit('pointerup',event(514));assert.equal(resumes.length,1);assert.equal(resumes[0],6);
run('playing=false;startScrub(ev)');emit('pointerup',event(474));assert.equal(resumes.length,1);
run('playing=true;startScrub(ev)');emit('pointercancel',{...event(474),type:'pointercancel'});assert.equal(resumes.length,1);
run('playing=true;startScrub(ev);pause()');emit('pointerup',event(474));assert.equal(resumes.length,1);
run('playing=true;startLasso(ev)');emit('pointerup',event(474));assert.equal(resumes.length,2);
console.log('Lecture : reprise après scrub/clic, maintien du silence à l’arrêt et aucune reprise après annulation/Stop : OK.');
// Inherited file labels follow renames; explicit block names survive, even
// when equal to the old file label. Clearing restores live inheritance.
run("playing=false;state.removedAssets=[];state.clips=[{...state.clips[0],id:'naming',name:'',nameOverride:false}];selectOnly('naming');render()");
const renameFile=name=>{const input=document.querySelector('[data-rename-asset]');input.value=name;input.onchange();};
renameFile('Entretien');assert.equal(run('clipName(state.clips[0])'),'Entretien');assert.equal(document.querySelector('.clip-name').textContent,'Entretien');
elements('clipName').value='Introduction';elements('clipName').onchange({target:elements('clipName')});renameFile('Entretien corrigé');assert.equal(run('clipName(state.clips[0])'),'Introduction');
elements('clipName').value='   ';elements('clipName').onchange({target:elements('clipName')});assert.equal(run('clipName(state.clips[0])'),'Entretien corrigé');renameFile('Prise finale');assert.equal(run('clipName(state.clips[0])'),'Prise finale');
elements('clipName').value='Prise finale';elements('clipName').onchange({target:elements('clipName')});renameFile('Autre nom');assert.equal(run('clipName(state.clips[0])'),'Prise finale');assert.equal(run('captureProject().state.clips[0].nameOverride'),true);
console.log('Noms : héritage dynamique, surcharge explicite et retour au fichier après effacement : OK.');
const originalTrackCount=run('state.tracks.length');context.confirm=()=>false;run('removeTrack(state.clips[0].track)');assert.equal(run('state.tracks.length'),originalTrackCount);context.confirm=()=>true;const mediaCount=run('projectAssets().length');run('removeTrack(state.clips[0].track)');assert.equal(run('state.tracks.length'),originalTrackCount-1);assert.equal(run('state.clips.length'),0);assert.equal(run('projectAssets().length'),mediaCount);run('undo()');assert.equal(run('state.tracks.length'),originalTrackCount);assert.equal(run('state.clips.length'),1);
run('for(const t of [...state.tracks])removeTrack(t.id)');assert.equal(run('state.tracks.length'),0);assert.equal((await run('hydrateProject(captureProject())')).state.tracks.length,0);document.querySelector('[data-add]').onclick();assert.equal(run('state.tracks.length'),1);assert.equal(run('state.clips.length'),1);
console.log('Suppression de piste : confirmation, fichiers conservés, annulation, projet sans piste et nouvel ajout audio : OK.');
